### PR TITLE
Added Local host

### PR DESCRIPTION
**Pull request by NamesCode**
I've added local host for those who self host SearXNG

### CODE REVIEW

**Comment by Sekki21956** [comment]
I'm not sure about this one, localhost:8080 is pretty generic and would interfere with a lot of other stuff that people could selfhost and could also cause problems for devs when testing their builds (local webserver etc.). @andreasgrafen @nekowinston what do you think?

**Comment by nekowinston** [comment]
> I'm not sure about this one, localhost:8080 is pretty generic and would interfere with a lot of other stuff that people could selfhost and could also cause problems for devs when testing their builds (local webserver etc.). @andreasgrafen @nekowinston what do you think?

Yeah, agreed. localhost **is** generic and will bleed into stuff you're developing locally.

**Comment by NamesCode** [comment]
Yeah true, Ive made my own custom one for localhost. If people want to have it they can do it themselves as its not that difficult

**Comment by NamesCode** [comment]
Closing this now. I will host a forked repo with local host support and update it whenever this port receives changes

**Pull request closed without merging**
